# Generated by Django 5.2.8 on 2025-11-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
